import i18n from 'i18next'
import { initReactI18next } from 'react-i18next'

export const languageOptions = [
  ['en', 'English'], ['es', 'Español'], ['pt', 'Português'], ['zh', '中文'], ['hi', 'हिन्दी'],
] as const
export const supportedLanguage = (code?: string) => languageOptions.some(([value]) => value === code) ? code! : 'en'

const en = { health: 'My health', plan: 'Care plan', history: 'History', profile: 'View profile', signOut: 'Sign out', language: 'Language', greeting: 'Good morning, {{name}}.', feeling: 'How are you feeling today?', tell: 'Tell us how you feel', speak: 'Speak instead', check: 'Check my symptoms', login: 'Sign in', create: 'Create my profile', welcome: 'Welcome back', email: 'Email address', password: 'Password', setup: 'Set up your profile', back: 'Back', later: 'You can change this later.', about: 'About you', fullName: 'Full name', birthday: 'Date of birth', phone: 'Mobile phone', reminders: 'Send text reminders for medicines and appointments.', healthInfo: 'Health information', conditions: 'Health conditions', allergies: 'Allergies', medications: 'Medications', add: 'Add another', medicineName: 'Name', dose: 'Dose', schedule: 'When do you take it?', routine: 'Routine or diet', instruction: 'Care instruction', appointment: 'Appointment', dateTime: 'Date and time', location: 'Location', emergency: 'Emergency contact', relationship: 'Relationship', save: 'Save profile', none: 'None added.', dailyRoutine: 'Daily routine', instructions: 'Care instructions', unsupported: 'This language is not available yet. English is shown.', guidance: 'Next step', emergencyText: 'If this is an emergency, call 911.' }
const es = { health: 'Mi salud', plan: 'Plan de cuidado', history: 'Historial', profile: 'Ver perfil', signOut: 'Cerrar sesión', language: 'Idioma', greeting: 'Buenos días, {{name}}.', feeling: '¿Cómo se siente hoy?', tell: 'Cuéntenos cómo se siente', speak: 'Hablar en su lugar', check: 'Revisar mis síntomas', login: 'Iniciar sesión', create: 'Crear mi perfil', welcome: 'Bienvenido de nuevo', email: 'Correo electrónico', password: 'Contraseña', setup: 'Configure su perfil', back: 'Volver', later: 'Puede cambiar esto más tarde.', about: 'Sobre usted', fullName: 'Nombre completo', birthday: 'Fecha de nacimiento', phone: 'Teléfono móvil', reminders: 'Enviarme recordatorios de medicamentos y citas.', healthInfo: 'Información de salud', conditions: 'Condiciones de salud', allergies: 'Alergias', medications: 'Medicamentos', add: 'Agregar otro', medicineName: 'Nombre', dose: 'Dosis', schedule: '¿Cuándo lo toma?', routine: 'Rutina o dieta', instruction: 'Instrucción de cuidado', appointment: 'Cita', dateTime: 'Fecha y hora', location: 'Lugar', emergency: 'Contacto de emergencia', relationship: 'Relación', save: 'Guardar perfil', none: 'No se agregó nada.', dailyRoutine: 'Rutina diaria', instructions: 'Instrucciones de cuidado', unsupported: 'Este idioma aún no está disponible. Se muestra inglés.', guidance: 'Próximo paso', emergencyText: 'Si es una emergencia, llame al 911.' }
const pt = { ...en, health: 'Minha saúde', plan: 'Plano de cuidados', history: 'Histórico', profile: 'Ver perfil', signOut: 'Sair', language: 'Idioma', greeting: 'Bom dia, {{name}}.', feeling: 'Como você está se sentindo hoje?', tell: 'Conte-nos como você se sente', speak: 'Falar em vez disso', check: 'Verificar meus sintomas', login: 'Entrar', create: 'Criar meu perfil', welcome: 'Bem-vindo de volta', setup: 'Crie seu perfil', back: 'Voltar', later: 'Você pode mudar isso depois.', emergency: 'Contato de emergência', unsupported: 'Este idioma ainda não está disponível. O inglês é exibido.', guidance: 'Próximo passo', emergencyText: 'Se for uma emergência, ligue para 911.' }
const zh = { ...en, health: '我的健康', plan: '护理计划', history: '历史记录', profile: '查看个人资料', signOut: '退出登录', language: '语言', greeting: '早上好，{{name}}。', feeling: '您今天感觉怎么样？', tell: '告诉我们您的感受', speak: '语音输入', check: '查看我的症状', login: '登录', create: '创建我的资料', welcome: '欢迎回来', setup: '设置您的资料', back: '返回', later: '您之后可以修改。', emergency: '紧急联系人', unsupported: '暂不支持此语言，现显示英语。', guidance: '下一步', emergencyText: '如遇紧急情况，请拨打 911。' }
const hi = { ...en, health: 'मेरा स्वास्थ्य', plan: 'देखभाल योजना', history: 'इतिहास', profile: 'प्रोफ़ाइल देखें', signOut: 'साइन आउट', language: 'भाषा', greeting: 'सुप्रभात, {{name}}।', feeling: 'आज आप कैसा महसूस कर रहे हैं?', tell: 'बताएं कि आप कैसा महसूस कर रहे हैं', speak: 'बोलकर बताएं', check: 'मेरे लक्षण देखें', login: 'साइन इन', create: 'मेरी प्रोफ़ाइल बनाएं', welcome: 'वापस स्वागत है', setup: 'अपनी प्रोफ़ाइल बनाएं', back: 'वापस', later: 'आप इसे बाद में बदल सकते हैं।', emergency: 'आपातकालीन संपर्क', unsupported: 'यह भाषा अभी उपलब्ध नहीं है। अंग्रेज़ी दिखाई जा रही है।', guidance: 'अगला कदम', emergencyText: 'आपात स्थिति में 911 पर कॉल करें।' }

i18n.use(initReactI18next).init({ resources: { en: { translation: en }, es: { translation: es }, pt: { translation: pt }, zh: { translation: zh }, hi: { translation: hi } }, fallbackLng: 'en', lng: 'en', interpolation: { escapeValue: false } })
export default i18n
